### ISSUE TITLE
Class name change

### ISSUE THREAD

**Issue by MaksManowski** [AnsonLai/MuseScore-Printer#1]
The class name has changed to "_2KmA_"

Also I think it would be more efficient to include printing inside the code (optionally).
New code:
`var temporary_el = document.createElement("DIV");
     var sheets = document.getElementsByClassName("_2KmA_");
     for (i = 0; i < sheets.length; i++) {
       sheets[i].alt = "";
       console.log(sheets[i]);
       temporary_el.appendChild(sheets[i].cloneNode(true));
 };
 var html = document.getElementsByTagName("html")[0];
 html.innerHTML = '';
 document.getElementsByTagName("body")[0].remove();
 html.appendChild(temporary_el);
 window.print();`

**Comment by AnsonLai** [comment]
Thank you, updated!  And I think the window.print() is a great idea!
