### ISSUE TITLE
Not working anymore.

### ISSUE THREAD

**Issue by pavelperc** [AnsonLai/MuseScore-Printer#2]
I'm sorry, it's not working anymore.
![image](https://user-images.githubusercontent.com/31820550/144715634-74376eed-b759-4bb1-9a4e-5f77cf9bf459.png)
Can you please fix it?

**Comment by AnsonLai** [comment]
Thanks for letting me know.  They changed the class names, so it was a quick fix.  Try running the new code, it's working on my end now.
