### ISSUE TITLE
Not working anymore again

### ISSUE THREAD

**Issue by Reqrefusion** [AnsonLai/MuseScore-Printer#3]
The code currently just outputs a white screen with a link

**Comment by RdStudios9145** [comment]
Hello!
To get it to work, change the "vAVs3" in the second line to "Hn_kk"
I have already submitted a request for the change in the repo, but I am not the owner and they may take some time to fix it.

**Comment by AnsonLai** [comment]
Thanks so much.  Just ran a few tests, the change works and it's been submitted.  Cheers!
