### ISSUE TITLE
For multi-page scores, only prints the current page

### ISSUE THREAD

**Issue by HumingCloud** [AnsonLai/MuseScore-Printer#5]
For example, on https://musescore.com/user/19710/scores/58553 , it only loads the first page to print. I have made sure to load every page, but that does not seem to work. I am using Brave, which is derived from Chromium.

**Comment by AnsonLai** [comment]
Sorry, I just fixed up the search.  The scale is a bit weird but if you print and set the scale to 25% it should be okay.  I'll have to dig into this later to see if there's a way to get the page to resize.  Bit weird.
